version: '3.7'
services:
  app:
    build: .
    tty: true
    ports:
      - 3005:3005
      - 5555:5555
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ../230213_learning04_db/postgres/init.d:/docker-entrypoint-initdb.d
      - ../230213_learning04_db/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: ${POSTGRES_DB}
    hostname: ${DB_HOSTNAME}
    restart: always
    user: ${DB_USER}
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ../230213_learning04_db/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
networks:
  lesson:
